#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCMS_WPF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="D:\\USERS\\PETER\\DOCUMENTS\\VISUAL STUDIO 2017\\PROJEKTE\\BOOKCMS-LOCALDB\\BOOKCMS-LOCA" +
		"LDB\\BIN\\DEBUG\\BOOKSQL-DB.MDF")]
	public partial class BuchDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void InsertAutorBuchLink(AutorBuchLink instance);
    partial void UpdateAutorBuchLink(AutorBuchLink instance);
    partial void DeleteAutorBuchLink(AutorBuchLink instance);
    partial void InsertAutorRolle(AutorRolle instance);
    partial void UpdateAutorRolle(AutorRolle instance);
    partial void DeleteAutorRolle(AutorRolle instance);
    #endregion
		
		public BuchDataClassesDataContext() : 
				base(global::BookCMS_WPF.Properties.Settings.Default.D__USERS_PETER_DOCUMENTS_VISUAL_STUDIO_2017_PROJEKTE_BOOKCMS_LOCALDB_BOOKCMS_LOCALDB_BIN_DEBUG_BOOKSQL_DB_MDFConnectionS, mappingSource)
		{
			OnCreated();
		}
		
		public BuchDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BuchDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BuchDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BuchDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AutorBuchLink> AutorBuchLink
		{
			get
			{
				return this.GetTable<AutorBuchLink>();
			}
		}
		
		public System.Data.Linq.Table<AutorRolle> AutorRolle
		{
			get
			{
				return this.GetTable<AutorRolle>();
			}
		}
		
		public System.Data.Linq.Table<Person> Person
		{
			get
			{
				return this.GetTable<Person>();
			}
		}
		
		public System.Data.Linq.Table<PersonRolle> PersonRolle
		{
			get
			{
				return this.GetTable<PersonRolle>();
			}
		}
		
		public System.Data.Linq.Table<Verlag> Verlag
		{
			get
			{
				return this.GetTable<Verlag>();
			}
		}
		
		public System.Data.Linq.Table<Kategorie> Kategorie
		{
			get
			{
				return this.GetTable<Kategorie>();
			}
		}
		
		public System.Data.Linq.Table<Sachgruppe> Sachgruppe
		{
			get
			{
				return this.GetTable<Sachgruppe>();
			}
		}
		
		public System.Data.Linq.Table<Person1> Person1
		{
			get
			{
				return this.GetTable<Person1>();
			}
		}
		
		public System.Data.Linq.Table<BuchTyp> BuchTyp
		{
			get
			{
				return this.GetTable<BuchTyp>();
			}
		}
		
		public System.Data.Linq.Table<VerlagsOrt> VerlagsOrt
		{
			get
			{
				return this.GetTable<VerlagsOrt>();
			}
		}
		
		public System.Data.Linq.Table<Druckerei> Druckerei
		{
			get
			{
				return this.GetTable<Druckerei>();
			}
		}
		
		public System.Data.Linq.Table<Bindung> Bindung
		{
			get
			{
				return this.GetTable<Bindung>();
			}
		}
		
		public System.Data.Linq.Table<Language> Language
		{
			get
			{
				return this.GetTable<Language>();
			}
		}
		
		public System.Data.Linq.Table<Buch> Buch
		{
			get
			{
				return this.GetTable<Buch>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AutorBuchLink")]
	public partial class AutorBuchLink : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _BuchID;
		
		private int _PersonID;
		
		private int _RolleID;
		
		private EntitySet<AutorRolle> _AutorRolle;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnBuchIDChanging(int value);
    partial void OnBuchIDChanged();
    partial void OnPersonIDChanging(int value);
    partial void OnPersonIDChanged();
    partial void OnRolleIDChanging(int value);
    partial void OnRolleIDChanged();
    #endregion
		
		public AutorBuchLink()
		{
			this._AutorRolle = new EntitySet<AutorRolle>(new Action<AutorRolle>(this.attach_AutorRolle), new Action<AutorRolle>(this.detach_AutorRolle));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuchID", DbType="Int NOT NULL")]
		public int BuchID
		{
			get
			{
				return this._BuchID;
			}
			set
			{
				if ((this._BuchID != value))
				{
					this.OnBuchIDChanging(value);
					this.SendPropertyChanging();
					this._BuchID = value;
					this.SendPropertyChanged("BuchID");
					this.OnBuchIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonID", DbType="Int NOT NULL")]
		public int PersonID
		{
			get
			{
				return this._PersonID;
			}
			set
			{
				if ((this._PersonID != value))
				{
					this.OnPersonIDChanging(value);
					this.SendPropertyChanging();
					this._PersonID = value;
					this.SendPropertyChanged("PersonID");
					this.OnPersonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RolleID", DbType="Int NOT NULL")]
		public int RolleID
		{
			get
			{
				return this._RolleID;
			}
			set
			{
				if ((this._RolleID != value))
				{
					this.OnRolleIDChanging(value);
					this.SendPropertyChanging();
					this._RolleID = value;
					this.SendPropertyChanged("RolleID");
					this.OnRolleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AutorBuchLink_AutorRolle", Storage="_AutorRolle", ThisKey="RolleID", OtherKey="ID")]
		public EntitySet<AutorRolle> AutorRolle
		{
			get
			{
				return this._AutorRolle;
			}
			set
			{
				this._AutorRolle.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AutorRolle(AutorRolle entity)
		{
			this.SendPropertyChanging();
			entity.AutorBuchLink = this;
		}
		
		private void detach_AutorRolle(AutorRolle entity)
		{
			this.SendPropertyChanging();
			entity.AutorBuchLink = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AutorRolle")]
	public partial class AutorRolle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<bool> _Marked;
		
		private string _AutorRolle1;
		
		private string _AutorKurz;
		
		private string _Notiz_PlainText;
		
		private EntityRef<AutorBuchLink> _AutorBuchLink;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMarkedChanging(System.Nullable<bool> value);
    partial void OnMarkedChanged();
    partial void OnAutorRolle1Changing(string value);
    partial void OnAutorRolle1Changed();
    partial void OnAutorKurzChanging(string value);
    partial void OnAutorKurzChanged();
    partial void OnNotiz_PlainTextChanging(string value);
    partial void OnNotiz_PlainTextChanged();
    #endregion
		
		public AutorRolle()
		{
			this._AutorBuchLink = default(EntityRef<AutorBuchLink>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._AutorBuchLink.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marked", DbType="Bit")]
		public System.Nullable<bool> Marked
		{
			get
			{
				return this._Marked;
			}
			set
			{
				if ((this._Marked != value))
				{
					this.OnMarkedChanging(value);
					this.SendPropertyChanging();
					this._Marked = value;
					this.SendPropertyChanged("Marked");
					this.OnMarkedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AutorRolle", Storage="_AutorRolle1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AutorRolle1
		{
			get
			{
				return this._AutorRolle1;
			}
			set
			{
				if ((this._AutorRolle1 != value))
				{
					this.OnAutorRolle1Changing(value);
					this.SendPropertyChanging();
					this._AutorRolle1 = value;
					this.SendPropertyChanged("AutorRolle1");
					this.OnAutorRolle1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutorKurz", DbType="NVarChar(10)")]
		public string AutorKurz
		{
			get
			{
				return this._AutorKurz;
			}
			set
			{
				if ((this._AutorKurz != value))
				{
					this.OnAutorKurzChanging(value);
					this.SendPropertyChanging();
					this._AutorKurz = value;
					this.SendPropertyChanged("AutorKurz");
					this.OnAutorKurzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notiz_PlainText", DbType="NVarChar(MAX)")]
		public string Notiz_PlainText
		{
			get
			{
				return this._Notiz_PlainText;
			}
			set
			{
				if ((this._Notiz_PlainText != value))
				{
					this.OnNotiz_PlainTextChanging(value);
					this.SendPropertyChanging();
					this._Notiz_PlainText = value;
					this.SendPropertyChanged("Notiz_PlainText");
					this.OnNotiz_PlainTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AutorBuchLink_AutorRolle", Storage="_AutorBuchLink", ThisKey="ID", OtherKey="RolleID", IsForeignKey=true)]
		public AutorBuchLink AutorBuchLink
		{
			get
			{
				return this._AutorBuchLink.Entity;
			}
			set
			{
				AutorBuchLink previousValue = this._AutorBuchLink.Entity;
				if (((previousValue != value) 
							|| (this._AutorBuchLink.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AutorBuchLink.Entity = null;
						previousValue.AutorRolle.Remove(this);
					}
					this._AutorBuchLink.Entity = value;
					if ((value != null))
					{
						value.AutorRolle.Add(this);
						this._ID = value.RolleID;
					}
					else
					{
						this._ID = default(int);
					}
					this.SendPropertyChanged("AutorBuchLink");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Person")]
	public partial class Person
	{
		
		private int _PersonID;
		
		private bool _Marked;
		
		private string _Name;
		
		private string _SortBy;
		
		private string _Geboren;
		
		private string _Gestorbe;
		
		private System.Nullable<int> _LandID;
		
		private string _Notiz_PlainText;
		
		private string _WWW;
		
		private string _Email;
		
		private string _Adresse_PlainText;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _Geburtsname;
		
		private string _Geburtzort;
		
		private string _Sterbeort;
		
		private string _Biografie_PlainText;
		
		public Person()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonID", DbType="Int NOT NULL")]
		public int PersonID
		{
			get
			{
				return this._PersonID;
			}
			set
			{
				if ((this._PersonID != value))
				{
					this._PersonID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marked", DbType="Bit NOT NULL")]
		public bool Marked
		{
			get
			{
				return this._Marked;
			}
			set
			{
				if ((this._Marked != value))
				{
					this._Marked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortBy", DbType="NVarChar(152)")]
		public string SortBy
		{
			get
			{
				return this._SortBy;
			}
			set
			{
				if ((this._SortBy != value))
				{
					this._SortBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geboren", DbType="NVarChar(8)")]
		public string Geboren
		{
			get
			{
				return this._Geboren;
			}
			set
			{
				if ((this._Geboren != value))
				{
					this._Geboren = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gestorbe", DbType="NVarChar(8)")]
		public string Gestorbe
		{
			get
			{
				return this._Gestorbe;
			}
			set
			{
				if ((this._Gestorbe != value))
				{
					this._Gestorbe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandID", DbType="Int")]
		public System.Nullable<int> LandID
		{
			get
			{
				return this._LandID;
			}
			set
			{
				if ((this._LandID != value))
				{
					this._LandID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notiz_PlainText", DbType="NVarChar(MAX)")]
		public string Notiz_PlainText
		{
			get
			{
				return this._Notiz_PlainText;
			}
			set
			{
				if ((this._Notiz_PlainText != value))
				{
					this._Notiz_PlainText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WWW", DbType="NVarChar(100)")]
		public string WWW
		{
			get
			{
				return this._WWW;
			}
			set
			{
				if ((this._WWW != value))
				{
					this._WWW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse_PlainText", DbType="NVarChar(MAX)")]
		public string Adresse_PlainText
		{
			get
			{
				return this._Adresse_PlainText;
			}
			set
			{
				if ((this._Adresse_PlainText != value))
				{
					this._Adresse_PlainText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(25)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(25)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geburtsname", DbType="NVarChar(100)")]
		public string Geburtsname
		{
			get
			{
				return this._Geburtsname;
			}
			set
			{
				if ((this._Geburtsname != value))
				{
					this._Geburtsname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geburtzort", DbType="NVarChar(150)")]
		public string Geburtzort
		{
			get
			{
				return this._Geburtzort;
			}
			set
			{
				if ((this._Geburtzort != value))
				{
					this._Geburtzort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterbeort", DbType="NVarChar(150)")]
		public string Sterbeort
		{
			get
			{
				return this._Sterbeort;
			}
			set
			{
				if ((this._Sterbeort != value))
				{
					this._Sterbeort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Biografie_PlainText", DbType="NVarChar(MAX)")]
		public string Biografie_PlainText
		{
			get
			{
				return this._Biografie_PlainText;
			}
			set
			{
				if ((this._Biografie_PlainText != value))
				{
					this._Biografie_PlainText = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonRolle")]
	public partial class PersonRolle
	{
		
		private int _PersonID;
		
		private System.Nullable<int> _RolleID;
		
		private string _SortBy;
		
		public PersonRolle()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonID", DbType="Int NOT NULL")]
		public int PersonID
		{
			get
			{
				return this._PersonID;
			}
			set
			{
				if ((this._PersonID != value))
				{
					this._PersonID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RolleID", DbType="Int")]
		public System.Nullable<int> RolleID
		{
			get
			{
				return this._RolleID;
			}
			set
			{
				if ((this._RolleID != value))
				{
					this._RolleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortBy", DbType="NVarChar(152) NOT NULL", CanBeNull=false)]
		public string SortBy
		{
			get
			{
				return this._SortBy;
			}
			set
			{
				if ((this._SortBy != value))
				{
					this._SortBy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Verlag")]
	public partial class Verlag
	{
		
		private int _PublisherID;
		
		private bool _Marked;
		
		private string _Verlag1;
		
		private string _SortBy;
		
		private string _Notiz_PlainText;
		
		private string _WWW;
		
		private string _Email;
		
		private string _Addresse_PlainText;
		
		private string _Phone;
		
		private string _Fax;
		
		public Verlag()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublisherID", DbType="Int NOT NULL")]
		public int PublisherID
		{
			get
			{
				return this._PublisherID;
			}
			set
			{
				if ((this._PublisherID != value))
				{
					this._PublisherID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marked", DbType="Bit NOT NULL")]
		public bool Marked
		{
			get
			{
				return this._Marked;
			}
			set
			{
				if ((this._Marked != value))
				{
					this._Marked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Verlag", Storage="_Verlag1", DbType="NVarChar(150)")]
		public string Verlag1
		{
			get
			{
				return this._Verlag1;
			}
			set
			{
				if ((this._Verlag1 != value))
				{
					this._Verlag1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortBy", DbType="NVarChar(152)")]
		public string SortBy
		{
			get
			{
				return this._SortBy;
			}
			set
			{
				if ((this._SortBy != value))
				{
					this._SortBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notiz_PlainText", DbType="NVarChar(MAX)")]
		public string Notiz_PlainText
		{
			get
			{
				return this._Notiz_PlainText;
			}
			set
			{
				if ((this._Notiz_PlainText != value))
				{
					this._Notiz_PlainText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WWW", DbType="NVarChar(100)")]
		public string WWW
		{
			get
			{
				return this._WWW;
			}
			set
			{
				if ((this._WWW != value))
				{
					this._WWW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addresse_PlainText", DbType="NVarChar(MAX)")]
		public string Addresse_PlainText
		{
			get
			{
				return this._Addresse_PlainText;
			}
			set
			{
				if ((this._Addresse_PlainText != value))
				{
					this._Addresse_PlainText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(25)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(25)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategorie")]
	public partial class Kategorie
	{
		
		private int _CategoryID;
		
		private bool _Marked;
		
		private string _Kategorie1;
		
		private string _SortBy;
		
		private string _Notiz_PlainText;
		
		public Kategorie()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="Int NOT NULL")]
		public int CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this._CategoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marked", DbType="Bit NOT NULL")]
		public bool Marked
		{
			get
			{
				return this._Marked;
			}
			set
			{
				if ((this._Marked != value))
				{
					this._Marked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Kategorie", Storage="_Kategorie1", DbType="NVarChar(50)")]
		public string Kategorie1
		{
			get
			{
				return this._Kategorie1;
			}
			set
			{
				if ((this._Kategorie1 != value))
				{
					this._Kategorie1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortBy", DbType="NVarChar(52)")]
		public string SortBy
		{
			get
			{
				return this._SortBy;
			}
			set
			{
				if ((this._SortBy != value))
				{
					this._SortBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notiz_PlainText", DbType="NVarChar(MAX)")]
		public string Notiz_PlainText
		{
			get
			{
				return this._Notiz_PlainText;
			}
			set
			{
				if ((this._Notiz_PlainText != value))
				{
					this._Notiz_PlainText = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sachgruppe")]
	public partial class Sachgruppe
	{
		
		private int _GenreID;
		
		private bool _Marked;
		
		private string _Sachgruppe1;
		
		private string _SortBy;
		
		private string _Notiz_PlainText;
		
		public Sachgruppe()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenreID", DbType="Int NOT NULL")]
		public int GenreID
		{
			get
			{
				return this._GenreID;
			}
			set
			{
				if ((this._GenreID != value))
				{
					this._GenreID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marked", DbType="Bit NOT NULL")]
		public bool Marked
		{
			get
			{
				return this._Marked;
			}
			set
			{
				if ((this._Marked != value))
				{
					this._Marked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Sachgruppe", Storage="_Sachgruppe1", DbType="NVarChar(50)")]
		public string Sachgruppe1
		{
			get
			{
				return this._Sachgruppe1;
			}
			set
			{
				if ((this._Sachgruppe1 != value))
				{
					this._Sachgruppe1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortBy", DbType="NVarChar(52)")]
		public string SortBy
		{
			get
			{
				return this._SortBy;
			}
			set
			{
				if ((this._SortBy != value))
				{
					this._SortBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notiz_PlainText", DbType="NVarChar(MAX)")]
		public string Notiz_PlainText
		{
			get
			{
				return this._Notiz_PlainText;
			}
			set
			{
				if ((this._Notiz_PlainText != value))
				{
					this._Notiz_PlainText = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Person")]
	public partial class Person1
	{
		
		private int _PersonID;
		
		private bool _Marked;
		
		private string _Name;
		
		private string _SortBy;
		
		private string _Geboren;
		
		private string _Gestorbe;
		
		private System.Nullable<int> _LandID;
		
		private string _Notiz_PlainText;
		
		private string _WWW;
		
		private string _Email;
		
		private string _Adresse_PlainText;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _Geburtsname;
		
		private string _Geburtzort;
		
		private string _Sterbeort;
		
		private string _Biografie_PlainText;
		
		public Person1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonID", DbType="Int NOT NULL")]
		public int PersonID
		{
			get
			{
				return this._PersonID;
			}
			set
			{
				if ((this._PersonID != value))
				{
					this._PersonID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marked", DbType="Bit NOT NULL")]
		public bool Marked
		{
			get
			{
				return this._Marked;
			}
			set
			{
				if ((this._Marked != value))
				{
					this._Marked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortBy", DbType="NVarChar(152)")]
		public string SortBy
		{
			get
			{
				return this._SortBy;
			}
			set
			{
				if ((this._SortBy != value))
				{
					this._SortBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geboren", DbType="NVarChar(8)")]
		public string Geboren
		{
			get
			{
				return this._Geboren;
			}
			set
			{
				if ((this._Geboren != value))
				{
					this._Geboren = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gestorbe", DbType="NVarChar(8)")]
		public string Gestorbe
		{
			get
			{
				return this._Gestorbe;
			}
			set
			{
				if ((this._Gestorbe != value))
				{
					this._Gestorbe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandID", DbType="Int")]
		public System.Nullable<int> LandID
		{
			get
			{
				return this._LandID;
			}
			set
			{
				if ((this._LandID != value))
				{
					this._LandID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notiz_PlainText", DbType="NVarChar(MAX)")]
		public string Notiz_PlainText
		{
			get
			{
				return this._Notiz_PlainText;
			}
			set
			{
				if ((this._Notiz_PlainText != value))
				{
					this._Notiz_PlainText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WWW", DbType="NVarChar(100)")]
		public string WWW
		{
			get
			{
				return this._WWW;
			}
			set
			{
				if ((this._WWW != value))
				{
					this._WWW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse_PlainText", DbType="NVarChar(MAX)")]
		public string Adresse_PlainText
		{
			get
			{
				return this._Adresse_PlainText;
			}
			set
			{
				if ((this._Adresse_PlainText != value))
				{
					this._Adresse_PlainText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(25)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(25)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geburtsname", DbType="NVarChar(100)")]
		public string Geburtsname
		{
			get
			{
				return this._Geburtsname;
			}
			set
			{
				if ((this._Geburtsname != value))
				{
					this._Geburtsname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geburtzort", DbType="NVarChar(150)")]
		public string Geburtzort
		{
			get
			{
				return this._Geburtzort;
			}
			set
			{
				if ((this._Geburtzort != value))
				{
					this._Geburtzort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sterbeort", DbType="NVarChar(150)")]
		public string Sterbeort
		{
			get
			{
				return this._Sterbeort;
			}
			set
			{
				if ((this._Sterbeort != value))
				{
					this._Sterbeort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Biografie_PlainText", DbType="NVarChar(MAX)")]
		public string Biografie_PlainText
		{
			get
			{
				return this._Biografie_PlainText;
			}
			set
			{
				if ((this._Biografie_PlainText != value))
				{
					this._Biografie_PlainText = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BuchTyp")]
	public partial class BuchTyp
	{
		
		private int _ID;
		
		private bool _Marked;
		
		private string _BuchTyp1;
		
		private string _SortBy;
		
		private string _Notiz_PlainText;
		
		private string _neu;
		
		public BuchTyp()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marked", DbType="Bit NOT NULL")]
		public bool Marked
		{
			get
			{
				return this._Marked;
			}
			set
			{
				if ((this._Marked != value))
				{
					this._Marked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="BuchTyp", Storage="_BuchTyp1", DbType="NVarChar(50)")]
		public string BuchTyp1
		{
			get
			{
				return this._BuchTyp1;
			}
			set
			{
				if ((this._BuchTyp1 != value))
				{
					this._BuchTyp1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortBy", DbType="NVarChar(52)")]
		public string SortBy
		{
			get
			{
				return this._SortBy;
			}
			set
			{
				if ((this._SortBy != value))
				{
					this._SortBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notiz_PlainText", DbType="NVarChar(MAX)")]
		public string Notiz_PlainText
		{
			get
			{
				return this._Notiz_PlainText;
			}
			set
			{
				if ((this._Notiz_PlainText != value))
				{
					this._Notiz_PlainText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_neu", DbType="NVarChar(255)")]
		public string neu
		{
			get
			{
				return this._neu;
			}
			set
			{
				if ((this._neu != value))
				{
					this._neu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VerlagsOrt")]
	public partial class VerlagsOrt
	{
		
		private int _ID;
		
		private bool _Marked;
		
		private string _Verlagsort1;
		
		private string _SortBy;
		
		private string _Notiz_PlainText;
		
		public VerlagsOrt()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marked", DbType="Bit NOT NULL")]
		public bool Marked
		{
			get
			{
				return this._Marked;
			}
			set
			{
				if ((this._Marked != value))
				{
					this._Marked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Verlagsort", Storage="_Verlagsort1", DbType="NVarChar(100)")]
		public string Verlagsort1
		{
			get
			{
				return this._Verlagsort1;
			}
			set
			{
				if ((this._Verlagsort1 != value))
				{
					this._Verlagsort1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortBy", DbType="NVarChar(102)")]
		public string SortBy
		{
			get
			{
				return this._SortBy;
			}
			set
			{
				if ((this._SortBy != value))
				{
					this._SortBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notiz_PlainText", DbType="NVarChar(MAX)")]
		public string Notiz_PlainText
		{
			get
			{
				return this._Notiz_PlainText;
			}
			set
			{
				if ((this._Notiz_PlainText != value))
				{
					this._Notiz_PlainText = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Druckerei")]
	public partial class Druckerei
	{
		
		private int _PrintedByID;
		
		private bool _Marked;
		
		private string _Druckerei1;
		
		private string _SortBy;
		
		private string _Notiz_PlainText;
		
		private string _WWW;
		
		private string _Email;
		
		private string _Adresse_PlainText;
		
		private string _Phone;
		
		private string _Fax;
		
		public Druckerei()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintedByID", DbType="Int NOT NULL")]
		public int PrintedByID
		{
			get
			{
				return this._PrintedByID;
			}
			set
			{
				if ((this._PrintedByID != value))
				{
					this._PrintedByID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marked", DbType="Bit NOT NULL")]
		public bool Marked
		{
			get
			{
				return this._Marked;
			}
			set
			{
				if ((this._Marked != value))
				{
					this._Marked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Druckerei", Storage="_Druckerei1", DbType="NVarChar(50)")]
		public string Druckerei1
		{
			get
			{
				return this._Druckerei1;
			}
			set
			{
				if ((this._Druckerei1 != value))
				{
					this._Druckerei1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortBy", DbType="NVarChar(52)")]
		public string SortBy
		{
			get
			{
				return this._SortBy;
			}
			set
			{
				if ((this._SortBy != value))
				{
					this._SortBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notiz_PlainText", DbType="NVarChar(MAX)")]
		public string Notiz_PlainText
		{
			get
			{
				return this._Notiz_PlainText;
			}
			set
			{
				if ((this._Notiz_PlainText != value))
				{
					this._Notiz_PlainText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WWW", DbType="NVarChar(100)")]
		public string WWW
		{
			get
			{
				return this._WWW;
			}
			set
			{
				if ((this._WWW != value))
				{
					this._WWW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse_PlainText", DbType="NVarChar(MAX)")]
		public string Adresse_PlainText
		{
			get
			{
				return this._Adresse_PlainText;
			}
			set
			{
				if ((this._Adresse_PlainText != value))
				{
					this._Adresse_PlainText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(25)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(25)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bindung")]
	public partial class Bindung
	{
		
		private int _BindingID;
		
		private bool _Marked;
		
		private string _Bindung1;
		
		private string _SortBy;
		
		private string _Notiz_PlainText;
		
		public Bindung()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BindingID", DbType="Int NOT NULL")]
		public int BindingID
		{
			get
			{
				return this._BindingID;
			}
			set
			{
				if ((this._BindingID != value))
				{
					this._BindingID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marked", DbType="Bit NOT NULL")]
		public bool Marked
		{
			get
			{
				return this._Marked;
			}
			set
			{
				if ((this._Marked != value))
				{
					this._Marked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Bindung", Storage="_Bindung1", DbType="NVarChar(50)")]
		public string Bindung1
		{
			get
			{
				return this._Bindung1;
			}
			set
			{
				if ((this._Bindung1 != value))
				{
					this._Bindung1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortBy", DbType="NVarChar(52)")]
		public string SortBy
		{
			get
			{
				return this._SortBy;
			}
			set
			{
				if ((this._SortBy != value))
				{
					this._SortBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notiz_PlainText", DbType="NVarChar(MAX)")]
		public string Notiz_PlainText
		{
			get
			{
				return this._Notiz_PlainText;
			}
			set
			{
				if ((this._Notiz_PlainText != value))
				{
					this._Notiz_PlainText = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Language")]
	public partial class Language
	{
		
		private int _LanguageID;
		
		private bool _Marked;
		
		private string _Language1;
		
		private string _SortBy;
		
		private string _Notiz_PlainText;
		
		private string _iso;
		
		public Language()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageID", DbType="Int NOT NULL")]
		public int LanguageID
		{
			get
			{
				return this._LanguageID;
			}
			set
			{
				if ((this._LanguageID != value))
				{
					this._LanguageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marked", DbType="Bit NOT NULL")]
		public bool Marked
		{
			get
			{
				return this._Marked;
			}
			set
			{
				if ((this._Marked != value))
				{
					this._Marked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Language", Storage="_Language1", DbType="NVarChar(50)")]
		public string Language1
		{
			get
			{
				return this._Language1;
			}
			set
			{
				if ((this._Language1 != value))
				{
					this._Language1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortBy", DbType="NVarChar(52)")]
		public string SortBy
		{
			get
			{
				return this._SortBy;
			}
			set
			{
				if ((this._SortBy != value))
				{
					this._SortBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notiz_PlainText", DbType="NVarChar(MAX)")]
		public string Notiz_PlainText
		{
			get
			{
				return this._Notiz_PlainText;
			}
			set
			{
				if ((this._Notiz_PlainText != value))
				{
					this._Notiz_PlainText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iso", DbType="NVarChar(255)")]
		public string iso
		{
			get
			{
				return this._iso;
			}
			set
			{
				if ((this._iso != value))
				{
					this._iso = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Buch")]
	public partial class Buch
	{
		
		private int _ID;
		
		private bool _Marked;
		
		private System.Nullable<short> _MediaCount;
		
		private string _Titel;
		
		private string _TitelIndex;
		
		private string _AutorSort;
		
		private string _Signatur;
		
		private string _Veroeffentlicht;
		
		private string _CopyrightDatum;
		
		private System.Nullable<int> _TypID;
		
		private string _Untertitel;
		
		private string _TitleSort;
		
		private System.Nullable<int> _VerlagsID;
		
		private string _ISBN;
		
		private string _DNB;
		
		private string _DDC;
		
		private string _LCCN;
		
		private string _LCCallNum;
		
		private System.Nullable<int> _LandD;
		
		private System.Nullable<int> _SprachenID;
		
		private System.Nullable<int> _DruckereiID;
		
		private System.Nullable<int> _BindungID;
		
		private System.Nullable<int> _AuflageID;
		
		private string _Auiflage;
		
		private System.Nullable<int> _DruckID;
		
		private System.Nullable<int> _SerienID;
		
		private string _Seiten;
		
		private System.Nullable<short> _Abschnitte;
		
		private string _OriginalTitel;
		
		private string _OriginalUntertitel;
		
		private System.Nullable<int> _OriginaVerlagID;
		
		private System.Nullable<int> _OriginalLandID;
		
		private System.Nullable<int> _OriginalSpracheID;
		
		private string _OriginalCopyright;
		
		private string _Preisangabe;
		
		private string _Value;
		
		private string _Preis;
		
		private System.Nullable<int> _ZustandID;
		
		private System.Nullable<int> _GutachterID;
		
		private System.Nullable<int> _Versicherung;
		
		private string _Registeriert;
		
		private System.Nullable<int> _StatusID;
		
		private string _Erworben;
		
		private System.Nullable<int> _ErworbenVonID;
		
		private System.Nullable<int> _PersonalRatingID;
		
		private System.Nullable<int> _BesitzerID;
		
		private System.Nullable<int> _StandortID;
		
		private System.Nullable<int> _EntleiherID;
		
		private string _DatumAusleihe;
		
		private string _RueckgabeDatum;
		
		private bool _verliehen;
		
		private bool _zurueckerhalten;
		
		private string _zurueckDatum;
		
		private System.Nullable<int> _zurueckVonID;
		
		private string _EmailOverdueDate;
		
		private string _EmailReminderDate;
		
		private string _EmailReservedDate;
		
		private string _Anmerkungen_PlainText;
		
		private string _Synopsis_PlainText;
		
		private string _Reviews_PlainText;
		
		private string _BarCode;
		
		private System.Nullable<int> _OriginalSerieID;
		
		private string _zuletztGelesen;
		
		private System.Nullable<short> _AnzahlGelesen;
		
		private System.Nullable<int> _ZustandSchutzumschlagID;
		
		private string _Dim_Width;
		
		private string _Dim_Height;
		
		private string _Dim_Depth;
		
		private string _Verkaufspreis;
		
		private System.Nullable<int> _WaehrungID;
		
		private System.Nullable<int> _VerlagsOrtID;
		
		private string _ASIN;
		
		private System.Nullable<System.DateTime> _LetzteAenderung;
		
		private string _FreigabeNr;
		
		private string _OriginalFreigabeNr;
		
		private System.Nullable<int> _KategorieID;
		
		private System.Nullable<int> _UnterkategorieID;
		
		private System.Nullable<int> _SachgruppeID;
		
		private string _Stichworte;
		
		public Buch()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marked", DbType="Bit NOT NULL")]
		public bool Marked
		{
			get
			{
				return this._Marked;
			}
			set
			{
				if ((this._Marked != value))
				{
					this._Marked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MediaCount", DbType="SmallInt")]
		public System.Nullable<short> MediaCount
		{
			get
			{
				return this._MediaCount;
			}
			set
			{
				if ((this._MediaCount != value))
				{
					this._MediaCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titel", DbType="NVarChar(253)")]
		public string Titel
		{
			get
			{
				return this._Titel;
			}
			set
			{
				if ((this._Titel != value))
				{
					this._Titel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitelIndex", DbType="NVarChar(20)")]
		public string TitelIndex
		{
			get
			{
				return this._TitelIndex;
			}
			set
			{
				if ((this._TitelIndex != value))
				{
					this._TitelIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutorSort", DbType="NVarChar(100)")]
		public string AutorSort
		{
			get
			{
				return this._AutorSort;
			}
			set
			{
				if ((this._AutorSort != value))
				{
					this._AutorSort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signatur", DbType="NVarChar(25)")]
		public string Signatur
		{
			get
			{
				return this._Signatur;
			}
			set
			{
				if ((this._Signatur != value))
				{
					this._Signatur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Veroeffentlicht", DbType="NVarChar(50)")]
		public string Veroeffentlicht
		{
			get
			{
				return this._Veroeffentlicht;
			}
			set
			{
				if ((this._Veroeffentlicht != value))
				{
					this._Veroeffentlicht = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CopyrightDatum", DbType="NVarChar(8)")]
		public string CopyrightDatum
		{
			get
			{
				return this._CopyrightDatum;
			}
			set
			{
				if ((this._CopyrightDatum != value))
				{
					this._CopyrightDatum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypID", DbType="Int")]
		public System.Nullable<int> TypID
		{
			get
			{
				return this._TypID;
			}
			set
			{
				if ((this._TypID != value))
				{
					this._TypID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Untertitel", DbType="NVarChar(255)")]
		public string Untertitel
		{
			get
			{
				return this._Untertitel;
			}
			set
			{
				if ((this._Untertitel != value))
				{
					this._Untertitel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleSort", DbType="NVarChar(255)")]
		public string TitleSort
		{
			get
			{
				return this._TitleSort;
			}
			set
			{
				if ((this._TitleSort != value))
				{
					this._TitleSort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerlagsID", DbType="Int")]
		public System.Nullable<int> VerlagsID
		{
			get
			{
				return this._VerlagsID;
			}
			set
			{
				if ((this._VerlagsID != value))
				{
					this._VerlagsID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="NVarChar(25)")]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this._ISBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNB", DbType="NVarChar(255)")]
		public string DNB
		{
			get
			{
				return this._DNB;
			}
			set
			{
				if ((this._DNB != value))
				{
					this._DNB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDC", DbType="NVarChar(100)")]
		public string DDC
		{
			get
			{
				return this._DDC;
			}
			set
			{
				if ((this._DDC != value))
				{
					this._DDC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCCN", DbType="NVarChar(50)")]
		public string LCCN
		{
			get
			{
				return this._LCCN;
			}
			set
			{
				if ((this._LCCN != value))
				{
					this._LCCN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LCCallNum", DbType="NVarChar(50)")]
		public string LCCallNum
		{
			get
			{
				return this._LCCallNum;
			}
			set
			{
				if ((this._LCCallNum != value))
				{
					this._LCCallNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandD", DbType="Int")]
		public System.Nullable<int> LandD
		{
			get
			{
				return this._LandD;
			}
			set
			{
				if ((this._LandD != value))
				{
					this._LandD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SprachenID", DbType="Int")]
		public System.Nullable<int> SprachenID
		{
			get
			{
				return this._SprachenID;
			}
			set
			{
				if ((this._SprachenID != value))
				{
					this._SprachenID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DruckereiID", DbType="Int")]
		public System.Nullable<int> DruckereiID
		{
			get
			{
				return this._DruckereiID;
			}
			set
			{
				if ((this._DruckereiID != value))
				{
					this._DruckereiID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BindungID", DbType="Int")]
		public System.Nullable<int> BindungID
		{
			get
			{
				return this._BindungID;
			}
			set
			{
				if ((this._BindungID != value))
				{
					this._BindungID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuflageID", DbType="Int")]
		public System.Nullable<int> AuflageID
		{
			get
			{
				return this._AuflageID;
			}
			set
			{
				if ((this._AuflageID != value))
				{
					this._AuflageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auiflage", DbType="NVarChar(255)")]
		public string Auiflage
		{
			get
			{
				return this._Auiflage;
			}
			set
			{
				if ((this._Auiflage != value))
				{
					this._Auiflage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DruckID", DbType="Int")]
		public System.Nullable<int> DruckID
		{
			get
			{
				return this._DruckID;
			}
			set
			{
				if ((this._DruckID != value))
				{
					this._DruckID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerienID", DbType="Int")]
		public System.Nullable<int> SerienID
		{
			get
			{
				return this._SerienID;
			}
			set
			{
				if ((this._SerienID != value))
				{
					this._SerienID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seiten", DbType="NVarChar(50)")]
		public string Seiten
		{
			get
			{
				return this._Seiten;
			}
			set
			{
				if ((this._Seiten != value))
				{
					this._Seiten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abschnitte", DbType="SmallInt")]
		public System.Nullable<short> Abschnitte
		{
			get
			{
				return this._Abschnitte;
			}
			set
			{
				if ((this._Abschnitte != value))
				{
					this._Abschnitte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalTitel", DbType="NVarChar(255)")]
		public string OriginalTitel
		{
			get
			{
				return this._OriginalTitel;
			}
			set
			{
				if ((this._OriginalTitel != value))
				{
					this._OriginalTitel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalUntertitel", DbType="NVarChar(255)")]
		public string OriginalUntertitel
		{
			get
			{
				return this._OriginalUntertitel;
			}
			set
			{
				if ((this._OriginalUntertitel != value))
				{
					this._OriginalUntertitel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginaVerlagID", DbType="Int")]
		public System.Nullable<int> OriginaVerlagID
		{
			get
			{
				return this._OriginaVerlagID;
			}
			set
			{
				if ((this._OriginaVerlagID != value))
				{
					this._OriginaVerlagID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalLandID", DbType="Int")]
		public System.Nullable<int> OriginalLandID
		{
			get
			{
				return this._OriginalLandID;
			}
			set
			{
				if ((this._OriginalLandID != value))
				{
					this._OriginalLandID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalSpracheID", DbType="Int")]
		public System.Nullable<int> OriginalSpracheID
		{
			get
			{
				return this._OriginalSpracheID;
			}
			set
			{
				if ((this._OriginalSpracheID != value))
				{
					this._OriginalSpracheID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalCopyright", DbType="NVarChar(8)")]
		public string OriginalCopyright
		{
			get
			{
				return this._OriginalCopyright;
			}
			set
			{
				if ((this._OriginalCopyright != value))
				{
					this._OriginalCopyright = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preisangabe", DbType="NVarChar(255)")]
		public string Preisangabe
		{
			get
			{
				return this._Preisangabe;
			}
			set
			{
				if ((this._Preisangabe != value))
				{
					this._Preisangabe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(255)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preis", DbType="NVarChar(255)")]
		public string Preis
		{
			get
			{
				return this._Preis;
			}
			set
			{
				if ((this._Preis != value))
				{
					this._Preis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZustandID", DbType="Int")]
		public System.Nullable<int> ZustandID
		{
			get
			{
				return this._ZustandID;
			}
			set
			{
				if ((this._ZustandID != value))
				{
					this._ZustandID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GutachterID", DbType="Int")]
		public System.Nullable<int> GutachterID
		{
			get
			{
				return this._GutachterID;
			}
			set
			{
				if ((this._GutachterID != value))
				{
					this._GutachterID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Versicherung", DbType="Int")]
		public System.Nullable<int> Versicherung
		{
			get
			{
				return this._Versicherung;
			}
			set
			{
				if ((this._Versicherung != value))
				{
					this._Versicherung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registeriert", DbType="NVarChar(8)")]
		public string Registeriert
		{
			get
			{
				return this._Registeriert;
			}
			set
			{
				if ((this._Registeriert != value))
				{
					this._Registeriert = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusID", DbType="Int")]
		public System.Nullable<int> StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				if ((this._StatusID != value))
				{
					this._StatusID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Erworben", DbType="NVarChar(8)")]
		public string Erworben
		{
			get
			{
				return this._Erworben;
			}
			set
			{
				if ((this._Erworben != value))
				{
					this._Erworben = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErworbenVonID", DbType="Int")]
		public System.Nullable<int> ErworbenVonID
		{
			get
			{
				return this._ErworbenVonID;
			}
			set
			{
				if ((this._ErworbenVonID != value))
				{
					this._ErworbenVonID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonalRatingID", DbType="Int")]
		public System.Nullable<int> PersonalRatingID
		{
			get
			{
				return this._PersonalRatingID;
			}
			set
			{
				if ((this._PersonalRatingID != value))
				{
					this._PersonalRatingID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BesitzerID", DbType="Int")]
		public System.Nullable<int> BesitzerID
		{
			get
			{
				return this._BesitzerID;
			}
			set
			{
				if ((this._BesitzerID != value))
				{
					this._BesitzerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandortID", DbType="Int")]
		public System.Nullable<int> StandortID
		{
			get
			{
				return this._StandortID;
			}
			set
			{
				if ((this._StandortID != value))
				{
					this._StandortID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntleiherID", DbType="Int")]
		public System.Nullable<int> EntleiherID
		{
			get
			{
				return this._EntleiherID;
			}
			set
			{
				if ((this._EntleiherID != value))
				{
					this._EntleiherID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumAusleihe", DbType="NVarChar(8)")]
		public string DatumAusleihe
		{
			get
			{
				return this._DatumAusleihe;
			}
			set
			{
				if ((this._DatumAusleihe != value))
				{
					this._DatumAusleihe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RueckgabeDatum", DbType="NVarChar(8)")]
		public string RueckgabeDatum
		{
			get
			{
				return this._RueckgabeDatum;
			}
			set
			{
				if ((this._RueckgabeDatum != value))
				{
					this._RueckgabeDatum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verliehen", DbType="Bit NOT NULL")]
		public bool verliehen
		{
			get
			{
				return this._verliehen;
			}
			set
			{
				if ((this._verliehen != value))
				{
					this._verliehen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zurueckerhalten", DbType="Bit NOT NULL")]
		public bool zurueckerhalten
		{
			get
			{
				return this._zurueckerhalten;
			}
			set
			{
				if ((this._zurueckerhalten != value))
				{
					this._zurueckerhalten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zurueckDatum", DbType="NVarChar(8)")]
		public string zurueckDatum
		{
			get
			{
				return this._zurueckDatum;
			}
			set
			{
				if ((this._zurueckDatum != value))
				{
					this._zurueckDatum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zurueckVonID", DbType="Int")]
		public System.Nullable<int> zurueckVonID
		{
			get
			{
				return this._zurueckVonID;
			}
			set
			{
				if ((this._zurueckVonID != value))
				{
					this._zurueckVonID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailOverdueDate", DbType="NVarChar(8)")]
		public string EmailOverdueDate
		{
			get
			{
				return this._EmailOverdueDate;
			}
			set
			{
				if ((this._EmailOverdueDate != value))
				{
					this._EmailOverdueDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailReminderDate", DbType="NVarChar(8)")]
		public string EmailReminderDate
		{
			get
			{
				return this._EmailReminderDate;
			}
			set
			{
				if ((this._EmailReminderDate != value))
				{
					this._EmailReminderDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailReservedDate", DbType="NVarChar(8)")]
		public string EmailReservedDate
		{
			get
			{
				return this._EmailReservedDate;
			}
			set
			{
				if ((this._EmailReservedDate != value))
				{
					this._EmailReservedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anmerkungen_PlainText", DbType="NVarChar(MAX)")]
		public string Anmerkungen_PlainText
		{
			get
			{
				return this._Anmerkungen_PlainText;
			}
			set
			{
				if ((this._Anmerkungen_PlainText != value))
				{
					this._Anmerkungen_PlainText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Synopsis_PlainText", DbType="NVarChar(MAX)")]
		public string Synopsis_PlainText
		{
			get
			{
				return this._Synopsis_PlainText;
			}
			set
			{
				if ((this._Synopsis_PlainText != value))
				{
					this._Synopsis_PlainText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reviews_PlainText", DbType="NVarChar(MAX)")]
		public string Reviews_PlainText
		{
			get
			{
				return this._Reviews_PlainText;
			}
			set
			{
				if ((this._Reviews_PlainText != value))
				{
					this._Reviews_PlainText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="NVarChar(50)")]
		public string BarCode
		{
			get
			{
				return this._BarCode;
			}
			set
			{
				if ((this._BarCode != value))
				{
					this._BarCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalSerieID", DbType="Int")]
		public System.Nullable<int> OriginalSerieID
		{
			get
			{
				return this._OriginalSerieID;
			}
			set
			{
				if ((this._OriginalSerieID != value))
				{
					this._OriginalSerieID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zuletztGelesen", DbType="NVarChar(8)")]
		public string zuletztGelesen
		{
			get
			{
				return this._zuletztGelesen;
			}
			set
			{
				if ((this._zuletztGelesen != value))
				{
					this._zuletztGelesen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnzahlGelesen", DbType="SmallInt")]
		public System.Nullable<short> AnzahlGelesen
		{
			get
			{
				return this._AnzahlGelesen;
			}
			set
			{
				if ((this._AnzahlGelesen != value))
				{
					this._AnzahlGelesen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZustandSchutzumschlagID", DbType="Int")]
		public System.Nullable<int> ZustandSchutzumschlagID
		{
			get
			{
				return this._ZustandSchutzumschlagID;
			}
			set
			{
				if ((this._ZustandSchutzumschlagID != value))
				{
					this._ZustandSchutzumschlagID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dim_Width", DbType="NVarChar(255)")]
		public string Dim_Width
		{
			get
			{
				return this._Dim_Width;
			}
			set
			{
				if ((this._Dim_Width != value))
				{
					this._Dim_Width = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dim_Height", DbType="NVarChar(255)")]
		public string Dim_Height
		{
			get
			{
				return this._Dim_Height;
			}
			set
			{
				if ((this._Dim_Height != value))
				{
					this._Dim_Height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dim_Depth", DbType="NVarChar(255)")]
		public string Dim_Depth
		{
			get
			{
				return this._Dim_Depth;
			}
			set
			{
				if ((this._Dim_Depth != value))
				{
					this._Dim_Depth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verkaufspreis", DbType="NVarChar(255)")]
		public string Verkaufspreis
		{
			get
			{
				return this._Verkaufspreis;
			}
			set
			{
				if ((this._Verkaufspreis != value))
				{
					this._Verkaufspreis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaehrungID", DbType="Int")]
		public System.Nullable<int> WaehrungID
		{
			get
			{
				return this._WaehrungID;
			}
			set
			{
				if ((this._WaehrungID != value))
				{
					this._WaehrungID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerlagsOrtID", DbType="Int")]
		public System.Nullable<int> VerlagsOrtID
		{
			get
			{
				return this._VerlagsOrtID;
			}
			set
			{
				if ((this._VerlagsOrtID != value))
				{
					this._VerlagsOrtID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASIN", DbType="NVarChar(20)")]
		public string ASIN
		{
			get
			{
				return this._ASIN;
			}
			set
			{
				if ((this._ASIN != value))
				{
					this._ASIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetzteAenderung", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> LetzteAenderung
		{
			get
			{
				return this._LetzteAenderung;
			}
			set
			{
				if ((this._LetzteAenderung != value))
				{
					this._LetzteAenderung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FreigabeNr", DbType="NVarChar(255)")]
		public string FreigabeNr
		{
			get
			{
				return this._FreigabeNr;
			}
			set
			{
				if ((this._FreigabeNr != value))
				{
					this._FreigabeNr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalFreigabeNr", DbType="NVarChar(255)")]
		public string OriginalFreigabeNr
		{
			get
			{
				return this._OriginalFreigabeNr;
			}
			set
			{
				if ((this._OriginalFreigabeNr != value))
				{
					this._OriginalFreigabeNr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategorieID", DbType="Int")]
		public System.Nullable<int> KategorieID
		{
			get
			{
				return this._KategorieID;
			}
			set
			{
				if ((this._KategorieID != value))
				{
					this._KategorieID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnterkategorieID", DbType="Int")]
		public System.Nullable<int> UnterkategorieID
		{
			get
			{
				return this._UnterkategorieID;
			}
			set
			{
				if ((this._UnterkategorieID != value))
				{
					this._UnterkategorieID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SachgruppeID", DbType="Int")]
		public System.Nullable<int> SachgruppeID
		{
			get
			{
				return this._SachgruppeID;
			}
			set
			{
				if ((this._SachgruppeID != value))
				{
					this._SachgruppeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stichworte", DbType="NVarChar(MAX)")]
		public string Stichworte
		{
			get
			{
				return this._Stichworte;
			}
			set
			{
				if ((this._Stichworte != value))
				{
					this._Stichworte = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
